name: new_tracking_workflow
channels:
  - anaconda
  - nvidia
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - aom=3.5.0=h27087fc_0
  - bottleneck=1.3.5=py37hda87dfa_0
  - brotli=1.0.9=h166bdaf_9
  - brotli-bin=1.0.9=h166bdaf_9
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2023.7.22=hbcca054_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.16.0=h0c91306_1017
  - cuda-nvcc=11.3.58=h2467b9f_0
  - cudatoolkit=11.3.1=hb98b00a_12
  - cudnn=8.2.1.32=h86fa8c9_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - dav1d=1.2.1=hd590300_0
  - expat=2.5.0=hcb278e6_1
  - ffmpeg=5.1.2=gpl_hcbfe3e7_111
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.38.0=py37h540881e_0
  - freetype=2.12.1=hca18f0e_1
  - fribidi=1.0.10=h36c2ea0_0
  - geos=3.9.1=h9c3ff4c_2
  - gettext=0.21.1=h27087fc_0
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.7.8=hf3e180e_0
  - graphite2=1.3.13=h58526e2_1001
  - h5py=3.1.0=nompi_py37h1e651dc_100
  - harfbuzz=8.1.1=h3d44ed6_1
  - hdf5=1.10.6=h3ffc7dd_1
  - icu=73.2=h59595ed_0
  - jpeg=9e=h0b41bf4_3
  - kiwisolver=1.4.4=py37h7cecad7_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - lerc=3.0=h9c3ff4c_0
  - libass=0.17.1=h8fe9dca_1
  - libblas=3.9.0=17_linux64_openblas
  - libbrotlicommon=1.0.9=h166bdaf_9
  - libbrotlidec=1.0.9=h166bdaf_9
  - libbrotlienc=1.0.9=h166bdaf_9
  - libcblas=3.9.0=17_linux64_openblas
  - libdeflate=1.10=h7f98852_0
  - libdrm=2.4.114=h166bdaf_0
  - libexpat=2.5.0=hcb278e6_1
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=13.1.0=he5830b7_0
  - libgfortran-ng=13.1.0=h69a702a_0
  - libgfortran5=13.1.0=h15d22d2_0
  - libglib=2.76.4=hebfc3b9_0
  - libgomp=13.1.0=he5830b7_0
  - libiconv=1.17=h166bdaf_0
  - libidn2=2.3.4=h166bdaf_0
  - liblapack=3.9.0=17_linux64_openblas
  - libnsl=2.0.0=h7f98852_0
  - libopenblas=0.3.23=pthreads_h80387f5_0
  - libopus=1.3.1=h7f98852_1
  - libpciaccess=0.17=h166bdaf_0
  - libpng=1.6.39=h753d276_0
  - libsqlite=3.43.0=h2797004_0
  - libstdcxx-ng=13.1.0=hfd8a6a1_0
  - libtasn1=4.19.0=h166bdaf_0
  - libtiff=4.3.0=h0fcbabc_4
  - libunistring=0.9.10=h7f98852_0
  - libuuid=2.38.1=h0b41bf4_0
  - libva=2.19.0=hd590300_0
  - libvpx=1.13.0=hcb278e6_0
  - libwebp-base=1.3.1=hd590300_0
  - libxcb=1.15=h0b41bf4_0
  - libxml2=2.11.5=h232c23b_1
  - libzlib=1.2.13=hd590300_5
  - matplotlib-base=3.5.3=py37hf395dca_2
  - munkres=1.1.4=pyh9f0ad1d_0
  - ncurses=6.4=hcb278e6_0
  - nettle=3.8.1=hc379101_1
  - nomkl=1.0=h5ca1d4c_0
  - numexpr=2.8.3=py37h85a3170_100
  - numpy=1.19.5=py37h3e96413_3
  - olefile=0.46=pyh9f0ad1d_1
  - openh264=2.3.1=hcb278e6_2
  - openjpeg=2.5.0=h7d73246_0
  - openssl=3.1.2=hd590300_0
  - p11-kit=0.24.1=hc5aa10d_0
  - pandas=1.3.5=py37h8c16a72_0
  - patsy=0.5.3=pyhd8ed1ab_0
  - pcre2=10.40=hc3806b6_0
  - pillow=8.4.0=py37h0f21c89_0
  - pip=23.2.1=pyhd8ed1ab_0
  - pixman=0.40.0=h36c2ea0_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - python=3.7.12=hf930737_100_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.7=3_cp37m
  - pytz=2023.3=pyhd8ed1ab_0
  - qtpy=2.3.1=pyhd8ed1ab_0
  - readline=8.2=h8228510_1
  - scipy=1.7.3=py37hf2a6cf1_0
  - seaborn-base=0.12.2=pyhd8ed1ab_0
  - setuptools=68.1.2=pyhd8ed1ab_0
  - shapely=1.7.1=py37h48c49eb_5
  - six=1.15.0=pyh9f0ad1d_0
  - sqlite=3.43.0=h2c6b66d_0
  - statsmodels=0.13.2=py37hda87dfa_0
  - svt-av1=1.4.1=hcb278e6_0
  - tk=8.6.12=h27826a3_0
  - typing_extensions=4.7.1=pyha770c72_0
  - unicodedata2=14.0.0=py37h540881e_1
  - wheel=0.41.2=pyhd8ed1ab_0
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xorg-fixesproto=5.0=h7f98852_1002
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.1.1=hd590300_0
  - xorg-libsm=1.2.4=h7391055_0
  - xorg-libx11=1.8.6=h8ee46fc_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.6=h166bdaf_0
  - zlib=1.2.13=hd590300_5
  - zstd=1.5.5=hfc55251_0
  - pip:
      - absl-py==0.15.0
      - astunparse==1.6.3
      - attrs==21.2.0
      - backports-zoneinfo==0.2.1
      - cachetools==4.2.4
      - cattrs==1.1.1
      - certifi==2021.10.8
      - charset-normalizer==2.0.12
      - clang==5.0
      - colorama==0.4.6
      - commonmark==0.9.1
      - efficientnet==1.0.0
      - et-xmlfile==1.1.0
      - flatbuffers==1.12
      - gast==0.4.0
      - google-auth==1.35.0
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - grpcio==1.44.0
      - hdmf==3.4.7
      - idna==3.3
      - image-classifiers==1.0.0
      - imageio==2.15.0
      - imgaug==0.4.0
      - imgstore==0.2.9
      - importlib-metadata==4.11.1
      - importlib-resources==5.10.0
      - joblib==1.2.0
      - jsmin==3.0.1
      - jsonpickle==1.2
      - jsonschema==4.17.0
      - keras==2.6.0
      - keras-applications==1.0.8
      - keras-preprocessing==1.1.2
      - markdown==3.3.6
      - ndx-pose==0.1.1
      - networkx==2.6.3
      - oauthlib==3.2.0
      - opencv-python==4.2.0.34
      - openpyxl==3.1.2
      - opt-einsum==3.3.0
      - packaging==21.3
      - pkgutil-resolve-name==1.3.10
      - protobuf==3.19.4
      - psutil==5.9.4
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pygments==2.13.0
      - pykalman==0.9.5
      - pynwb==2.2.0
      - pyparsing==3.0.7
      - pyrsistent==0.19.2
      - pyside2==5.14.1
      - python-rapidjson==1.9
      - pytz-deprecation-shim==0.1.0.post0
      - pywavelets==1.3.0
      - pyzmq==24.0.1
      - qimage2ndarray==1.9.0
      - requests==2.27.1
      - requests-oauthlib==1.3.1
      - rich==10.16.1
      - ruamel-yaml==0.17.21
      - ruamel-yaml-clib==0.2.7
      - scikit-image==0.19.3
      - scikit-learn==1.0.2
      - scikit-video==1.1.11
      - seaborn==0.12.1
      - segmentation-models==1.0.1
      - setuptools-scm==6.4.2
      - shiboken2==5.14.1
      - sleap==1.2.9
      - tensorboard==2.6.0
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorflow==2.6.3
      - tensorflow-estimator==2.6.0
      - termcolor==1.1.0
      - threadpoolctl==3.1.0
      - tifffile==2021.11.2
      - tomli==2.0.1
      - typing-extensions==3.10.0.2
      - tzdata==2022.6
      - tzlocal==4.2
      - urllib3==1.26.8
      - werkzeug==2.0.3
      - wrapt==1.12.1
      - zipp==3.7.0
prefix: /home/kosmas-deligkaris/mambaforge/envs/new_tracking_workflow
